# Basic Information 
title: Rongqi Bei
position: PhD Student
affiliation: University of Michigan
affiliation_link: https://www.si.umich.edu/
affiliation_logo: ./assets/img/illinois.svg
email: rbei@umich.edu

# Search Engine Optimization (SEO)
keywords: rongqi bei, bei rongqi, rongqibei, HCI, digital health, University of Michigan
canonical: https://rongqibei.com
description: Rongqi Bei is an HCI researcher and a second-year PhD student at the University of Michigan. Her work sits at the intersection of human-computer interaction (HCI) and digital health, focusing on designing technologies that support people's well-being in everyday life.

# The option is used to enable the Illinois template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: true

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?hl=en&user=qelg1bcAAAAJ&view_op=list_works&sortby=pubdate
#github_link: https://github.com/yaoyao-liu/
linkedin: https://www.linkedin.com/in/rongqi-bei/
#twitter: https://twitter.com/YaoyaoLiu1/
cv_link: ./assets/files/cv.pdf

# Images 
avatar: ./assets/img/rongqi-bei.png

# Footnotes
#footnote: Feel free to use my website's source code.
#footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
#clustrmaps_id: HV0rAUdAxpfEQLOsVs0FcJTR2rKVI5sEQUZIDM-N_HY

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
